# Generated by Django 2.0.2 on 2018-02-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=512)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpufrequency', models.FloatField()),
                ('cpu', models.TextField(max_length=200)),
                ('ram', models.IntegerField()),
                ('hdd', models.IntegerField()),
                ('imgpath', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Product')),
            ],
        ),
    ]
