# Generated by Django 2.0.2 on 2018-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='product',
        ),
        migrations.AlterField(
            model_name='specification',
            name='cpu',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='specification',
            name='cpufrequency',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='hdd',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='imgpath',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='specification',
            name='ram',
            field=models.IntegerField(blank=True),
        ),
    ]
